### ISSUE TITLE
Exception nas Barras de Vida

### ISSUE THREAD

**Issue by abbragaInf** [WinnySilva/WarDinos#1]
transform.localScale assign attempt for 'barradevida' is not valid. Input localScale is { NaN, 1.000000, 1.000000 }.
UnityEngine.Transform:set_localScale(Vector3)
GroupController:Update() (at Assets/Scripts/Gameplay/GroupController.cs:230)

Ocorre quando tenta-se criar um grupo com zero dinossauros.

**Comment by WinnySilva** [comment]
tu jah arrumou isso? pq não vi
